# Generated by Django 5.0.1 on 2025-12-27 22:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Cement, Steel, etc.)', max_length=255, unique=True)),
                ('url', models.URLField(blank=True, help_text='Category URL from source website', max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Category image URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the category is active and visible')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'), models.Index(fields=['is_active'], name='api_categor_is_acti_5fb091_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title/name', max_length=500)),
                ('url', models.URLField(blank=True, help_text='Product URL from source website', max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Main product image URL', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in rupees', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_display', models.CharField(blank=True, help_text="Original price string (e.g., 'Rs. 330.00')", max_length=50, null=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('limited', 'Limited stock')], default='in_stock', help_text='Product availability status', max_length=20)),
                ('product_id', models.CharField(blank=True, help_text='External product ID from source', max_length=100, null=True, unique=True)),
                ('variant_id', models.CharField(blank=True, help_text='Product variant ID', max_length=100, null=True)),
                ('description_text', models.TextField(blank=True, help_text='Product description in plain text', null=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of product image URLs')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Product specifications as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active and visible')),
                ('category', models.ForeignKey(help_text='Category this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='api_product_categor_5c53c5_idx'), models.Index(fields=['product_id'], name='api_product_product_aec78f_idx'), models.Index(fields=['is_active'], name='api_product_is_acti_b97ca3_idx'), models.Index(fields=['availability'], name='api_product_availab_16d936_idx'), models.Index(fields=['price'], name='api_product_price_b6b1d7_idx')],
            },
        ),
    ]
